/* ─── Helpers ─────────────────────────────────────────── */
export function genId() {
    return Math.random().toString(36).slice(2) + Date.now().toString(36)
}

/* Calcular fecha relativa a hoy para mock data */
export function daysAgo(n) {
    const d = new Date()
    d.setDate(d.getDate() - n)
    return d.toISOString().split('T')[0]
}

/* ─── Mock data ─────────────────────────────────────────── */
export const INITIAL_STUDENTS = [
    /* PREESCOLAR (6) */
    { id: genId(), nombre: 'Sofía', apellido: 'Ramírez Torres', nivel: 'preescolar', grado: 'Kínder 1', grupo: 'A', fechaNacimiento: '2022-04-10', curp: 'RATS220410MDFMRA09', nombrePadre: 'Arturo Ramírez', nombreMadre: 'Laura Torres', telefono: '(55) 3812-4561', email: 'ramirez.familia@email.com', direccion: 'Av. Juárez 45, Col. Centro', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(5) },
    { id: genId(), nombre: 'Emilio', apellido: 'Cruz Mendoza', nivel: 'preescolar', grado: 'Kínder 2', grupo: 'B', fechaNacimiento: '2021-07-22', curp: 'CUME210722HDFRZM04', nombrePadre: 'Hugo Cruz', nombreMadre: 'Valeria Mendoza', telefono: '(55) 2109-8734', email: 'cruz.hugo@email.com', direccion: 'Calle Morelos 12, Col. Juárez', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(40) },
    { id: genId(), nombre: 'Camila', apellido: 'Vega Soriano', nivel: 'preescolar', grado: 'Kínder 3', grupo: 'A', fechaNacimiento: '2020-11-03', curp: 'VESC201103MDFGRM07', nombrePadre: 'Marcos Vega', nombreMadre: 'Irene Soriano', telefono: '(55) 4456-7821', email: 'vega.familia@email.com', direccion: 'Calle Hidalgo 78, Col. Roma', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(10) },
    { id: genId(), nombre: 'Lucas', apellido: 'Flores Gutiérrez', nivel: 'preescolar', grado: 'Kínder 1', grupo: 'B', fechaNacimiento: '2022-01-15', curp: 'FOGL220115HDFRLC01', nombrePadre: 'Pedro Flores', nombreMadre: 'Ana Gutiérrez', telefono: '(55) 6634-9021', email: 'flores.pedro@email.com', direccion: 'Blvd. Insurgentes 200, Col. Doctores', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(28) },
    { id: genId(), nombre: 'Valentina', apellido: 'Ríos Castillo', nivel: 'preescolar', grado: 'Kínder 2', grupo: 'A', fechaNacimiento: '2021-09-30', curp: 'RICV210930MDFSVL05', nombrePadre: 'Juan Ríos', nombreMadre: 'Carmen Castillo', telefono: '(55) 8812-3340', email: 'rios.familia@email.com', direccion: 'Calle Reforma 500, Col. Polanco', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(15) },
    { id: genId(), nombre: 'Mateo', apellido: 'Herrera Díaz', nivel: 'preescolar', grado: 'Kínder 3', grupo: 'B', fechaNacimiento: '2020-06-18', curp: 'HEDM200618HDFRRT08', nombrePadre: 'Rodrigo Herrera', nombreMadre: 'Lucía Díaz', telefono: '(55) 1123-5678', email: 'herrera.lucía@email.com', direccion: 'Av. Álvaro Obregón 88, Col. Condesa', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(45) },

    /* PRIMARIA (8) */
    { id: genId(), nombre: 'Alejandro', apellido: 'Morales Reyes', nivel: 'primaria', grado: '3°', grupo: 'A', fechaNacimiento: '2016-03-12', curp: 'MORA160312HDFRLJ03', nombrePadre: 'José Morales', nombreMadre: 'Patricia Reyes', telefono: '(55) 5512-6789', email: 'morales.familia@email.com', direccion: 'Calle 5 de Mayo 33, Col. Guerrero', fechaInscripcion: '2023-08-15', ultimoPago: daysAgo(8) },
    { id: genId(), nombre: 'Isabella', apellido: 'López Vargas', nivel: 'primaria', grado: '1°', grupo: 'B', fechaNacimiento: '2018-08-25', curp: 'LOVI180825MDFLRB06', nombrePadre: 'Mario López', nombreMadre: 'Sandra Vargas', telefono: '(55) 3398-4412', email: 'lopez.mario@email.com', direccion: 'Av. Chapultepec 210, Col. Roma Norte', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(3) },
    { id: genId(), nombre: 'Sebastián', apellido: 'García Núñez', nivel: 'primaria', grado: '5°', grupo: 'A', fechaNacimiento: '2014-05-07', curp: 'GANS140507HDFRCB02', nombrePadre: 'Carlos García', nombreMadre: 'Elena Núñez', telefono: '(55) 7745-8823', email: 'garcia.carlos@email.com', direccion: 'Calle Insurgentes 99, Col. Nápoles', fechaInscripcion: '2022-08-10', ultimoPago: daysAgo(22) },
    { id: genId(), nombre: 'María José', apellido: 'Sánchez Peña', nivel: 'primaria', grado: '2°', grupo: 'B', fechaNacimiento: '2017-12-01', curp: 'SAPM171201MDFSRJ08', nombrePadre: 'Roberto Sánchez', nombreMadre: 'Guadalupe Peña', telefono: '(55) 9900-1122', email: 'sanchez.roberto@email.com', direccion: 'Calle Puebla 45, Col. Cuauhtémoc', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(50) },
    { id: genId(), nombre: 'Daniel', apellido: 'Mendoza Ruiz', nivel: 'primaria', grado: '4°', grupo: 'A', fechaNacimiento: '2015-02-14', curp: 'MERD150214HDFRDN09', nombrePadre: 'Ernesto Mendoza', nombreMadre: 'Rosa Ruiz', telefono: '(55) 4423-5500', email: 'mendoza.e@email.com', direccion: 'Av. Insurgentes Sur 450, Col. Del Valle', fechaInscripcion: '2022-08-10', ultimoPago: daysAgo(18) },
    { id: genId(), nombre: 'Mariana', apellido: 'Torres Jiménez', nivel: 'primaria', grado: '6°', grupo: 'B', fechaNacimiento: '2013-10-20', curp: 'TOJM131020MDFRRN07', nombrePadre: 'Luis Torres', nombreMadre: 'Norma Jiménez', telefono: '(55) 6612-7788', email: 'torres.luis@email.com', direccion: 'Calle Veracruz 12, Col. Hipódromo', fechaInscripcion: '2021-08-10', ultimoPago: daysAgo(1) },
    { id: genId(), nombre: 'Rodrigo', apellido: 'Ortiz Espinoza', nivel: 'primaria', grado: '2°', grupo: 'A', fechaNacimiento: '2017-06-08', curp: 'OIER170608HDFRDR04', nombrePadre: 'Alejandro Ortiz', nombreMadre: 'Fernanda Espinoza', telefono: '(55) 2234-4455', email: 'ortiz.ale@email.com', direccion: 'Calle Oaxaca 77, Col. Roma Sur', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(35) },
    { id: genId(), nombre: 'Andrea', apellido: 'Castro Montes', nivel: 'primaria', grado: '4°', grupo: 'B', fechaNacimiento: '2015-09-17', curp: 'CAMA150917MDFSSN01', nombrePadre: 'Felipe Castro', nombreMadre: 'Angélica Montes', telefono: '(55) 8899-0011', email: 'castro.familia@email.com', direccion: 'Av. Sonora 56, Col. Hipódromo Condesa', fechaInscripcion: '2022-08-10', ultimoPago: daysAgo(12) },

    /* SECUNDARIA (6) */
    { id: genId(), nombre: 'Luis Fernando', apellido: 'Martínez Ávila', nivel: 'secundaria', grado: '1°', grupo: 'A', fechaNacimiento: '2011-03-28', curp: 'MAAL110328HDFRVL05', nombrePadre: 'Fernando Martínez', nombreMadre: 'Gloria Ávila', telefono: '(55) 1100-2233', email: 'martinez.f@email.com', direccion: 'Calle Jalisco 99, Col. Portales', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(20) },
    { id: genId(), nombre: 'Fernanda', apellido: 'Gómez Serrano', nivel: 'secundaria', grado: '2°', grupo: 'B', fechaNacimiento: '2010-07-04', curp: 'GOSF100704MDFMRN02', nombrePadre: 'Alfredo Gómez', nombreMadre: 'Teresa Serrano', telefono: '(55) 3344-5566', email: 'gomez.alfredo@email.com', direccion: 'Calle Zacatecas 22, Col. Roma', fechaInscripcion: '2023-08-15', ultimoPago: daysAgo(60) },
    { id: genId(), nombre: 'Ángel', apellido: 'Reyes Fuentes', nivel: 'secundaria', grado: '3°', grupo: 'A', fechaNacimiento: '2009-11-14', curp: 'REFA091114HDFSVN07', nombrePadre: 'Enrique Reyes', nombreMadre: 'Beatriz Fuentes', telefono: '(55) 7788-9900', email: 'reyes.enrique@email.com', direccion: 'Calle Chihuahua 10, Col. Roma', fechaInscripcion: '2022-08-10', ultimoPago: daysAgo(4) },
    { id: genId(), nombre: 'Natalia', apellido: 'Jiménez Rojas', nivel: 'secundaria', grado: '1°', grupo: 'B', fechaNacimiento: '2011-05-30', curp: 'JIRN110530MDFRJT09', nombrePadre: 'Gerardo Jiménez', nombreMadre: 'Silvia Rojas', telefono: '(55) 5566-7788', email: 'jimenez.g@email.com', direccion: 'Blvd. Ávila Camacho 345, Col. Polanco', fechaInscripcion: '2024-08-01', ultimoPago: daysAgo(14) },
    { id: genId(), nombre: 'Diego', apellido: 'Pérez Villalobos', nivel: 'secundaria', grado: '2°', grupo: 'A', fechaNacimiento: '2010-02-09', curp: 'PEVD100209HDFRRL06', nombrePadre: 'Ricardo Pérez', nombreMadre: 'Mónica Villalobos', telefono: '(55) 9988-7766', email: 'perez.r@email.com', direccion: 'Calle Durango 88, Col. Roma Norte', fechaInscripcion: '2023-08-15', ultimoPago: daysAgo(29) },
    { id: genId(), nombre: 'Valeria', apellido: 'Navarro Salinas', nivel: 'secundaria', grado: '3°', grupo: 'B', fechaNacimiento: '2009-08-19', curp: 'NASV090819MDFRLL03', nombrePadre: 'Javier Navarro', nombreMadre: 'Alicia Salinas', telefono: '(55) 2211-3344', email: 'navarro.j@email.com', direccion: 'Av. Nuevo León 70, Col. Hipódromo', fechaInscripcion: '2022-08-10', ultimoPago: daysAgo(7) },
]
